#!/usr/bin/env python3
"""Example demonstrating Cartopy usage with downloaded BlueMarble backgrounds.

This script shows how to use the images.json file generated by cartopy-backgrounds
with Cartopy to create beautiful maps with NASA satellite imagery backgrounds.

Prerequisites:
    pip install cartopy matplotlib

Usage:
    1. First download images:
       cartopy-bg download --profile dev

    2. Generate images.json:
       cartopy-bg generate

    3. Run this example:
       python examples/cartopy_usage_example.py
"""

import os
import sys
from pathlib import Path

try:
    import cartopy.crs as ccrs
    import matplotlib.pyplot as plt
except ImportError:
    print("Error: cartopy and matplotlib are required to run this example.")
    print("Install them with: pip install cartopy matplotlib")
    sys.exit(1)


def setup_cartopy_backgrounds(images_json_path: Path) -> bool:
    """Setup Cartopy to use custom background images from images.json.

    Args:
        images_json_path: Path to images.json file

    Returns:
        True if successful, False otherwise
    """
    if not images_json_path.exists():
        print(f"Error: {images_json_path} not found.")
        print("Run 'cartopy-bg generate' first to create it.")
        return False

    # Set CARTOPY_USER_BACKGROUNDS to the directory containing images.json
    # Cartopy will automatically load images.json from this directory
    os.environ['CARTOPY_USER_BACKGROUNDS'] = str(images_json_path.parent)

    print(f"✓ Set CARTOPY_USER_BACKGROUNDS to: {images_json_path.parent}")
    print(f"✓ Cartopy will load backgrounds from: {images_json_path}")
    return True


def example_1_basic_map(output_path: Path) -> None:
    """Example 1: Basic map with BlueMarble background.

    Creates a simple global map with a BlueMarble January background.
    """
    print("Creating Example 1: Basic map with BlueMarble background...")

    fig = plt.figure(figsize=(12, 6))
    ax = fig.add_subplot(1, 1, 1, projection=ccrs.PlateCarree())

    # Add BlueMarble background (uses 'mid' resolution by default)
    ax.background_img(name="Blue Marble January", resolution="mid")

    # Add coastlines for reference
    ax.coastlines(linewidth=0.5, color="white", alpha=0.7)

    # Add gridlines
    gl = ax.gridlines(draw_labels=True, linewidth=0.5, alpha=0.5, linestyle="--")
    gl.top_labels = False
    gl.right_labels = False

    plt.title("Global Map with NASA BlueMarble Background (January)", fontsize=14, pad=15)

    plt.savefig(output_path, dpi=150, bbox_inches="tight")
    print(f"  ✓ Saved to {output_path}")
    plt.close()


def example_2_regional_map(output_path: Path) -> None:
    """Example 2: Regional map focused on Europe.

    Shows how to zoom into a specific region while using BlueMarble background.
    """
    print("Creating Example 2: Regional map (Europe)...")

    fig = plt.figure(figsize=(12, 8))
    ax = fig.add_subplot(1, 1, 1, projection=ccrs.PlateCarree())

    # Add BlueMarble background
    ax.background_img(name="Blue Marble July", resolution="mid")

    # Set extent to Europe
    ax.set_extent([-15, 40, 35, 72], crs=ccrs.PlateCarree())

    # Add features
    ax.coastlines(linewidth=0.8, color="white")
    ax.gridlines(draw_labels=True, linewidth=0.5, alpha=0.5)

    plt.title("European Region - July", fontsize=14, pad=15)

    plt.savefig(output_path, dpi=150, bbox_inches="tight")
    print(f"  ✓ Saved to {output_path}")
    plt.close()


def example_3_different_projections(output_path: Path) -> None:
    """Example 3: Multiple projections comparison.

    Demonstrates BlueMarble backgrounds with different map projections.
    """
    print("Creating Example 3: Different projections...")

    fig = plt.figure(figsize=(16, 10))

    # PlateCarree (equirectangular)
    ax1 = fig.add_subplot(2, 2, 1, projection=ccrs.PlateCarree())
    ax1.background_img(name="Blue Marble April", resolution="mid")
    ax1.coastlines(linewidth=0.5, color="white", alpha=0.7)
    ax1.set_title("PlateCarree Projection")

    # Orthographic (globe view) - North Pole
    ax2 = fig.add_subplot(2, 2, 2, projection=ccrs.Orthographic(0, 90))
    ax2.background_img(name="Blue Marble April", resolution="mid")
    ax2.coastlines(linewidth=0.5, color="white", alpha=0.7)
    ax2.set_title("Orthographic - North Pole")

    # Mollweide (elliptical)
    ax3 = fig.add_subplot(2, 2, 3, projection=ccrs.Mollweide())
    ax3.background_img(name="Blue Marble April", resolution="mid")
    ax3.coastlines(linewidth=0.5, color="white", alpha=0.7)
    ax3.set_title("Mollweide Projection")

    # Robinson
    ax4 = fig.add_subplot(2, 2, 4, projection=ccrs.Robinson())
    ax4.background_img(name="Blue Marble April", resolution="mid")
    ax4.coastlines(linewidth=0.5, color="white", alpha=0.7)
    ax4.set_title("Robinson Projection")

    plt.suptitle("BlueMarble April - Different Projections", fontsize=16, y=0.98)

    plt.savefig(output_path, dpi=150, bbox_inches="tight")
    print(f"  ✓ Saved to {output_path}")
    plt.close()


def example_4_seasonal_comparison(output_path: Path) -> None:
    """Example 4: Seasonal comparison.

    Shows the same region across different months to visualize seasonal changes.
    """
    print("Creating Example 4: Seasonal comparison...")

    fig = plt.figure(figsize=(16, 8))

    months = ["January", "April", "July", "October"]

    for idx, month in enumerate(months, 1):
        ax = fig.add_subplot(2, 2, idx, projection=ccrs.PlateCarree())
        ax.background_img(name=f"Blue Marble {month}", resolution="mid")

        # Focus on North America
        ax.set_extent([-130, -60, 25, 50], crs=ccrs.PlateCarree())
        ax.coastlines(linewidth=0.5, color="white", alpha=0.8)

        ax.set_title(month, fontsize=12)

    plt.suptitle("Seasonal Changes - North America", fontsize=16, y=0.98)

    plt.savefig(output_path, dpi=150, bbox_inches="tight")
    print(f"  ✓ Saved to {output_path}")
    plt.close()


def example_5_resolution_comparison(output_path: Path) -> None:
    """Example 5: Resolution comparison.

    Shows the difference between low, mid, and high resolution backgrounds.
    """
    print("Creating Example 5: Resolution comparison...")

    fig = plt.figure(figsize=(16, 5))

    resolutions = [("low", "720x360"), ("mid", "1440x720"), ("high", "3600x1800")]

    for idx, (res_name, res_size) in enumerate(resolutions, 1):
        ax = fig.add_subplot(1, 3, idx, projection=ccrs.PlateCarree())

        try:
            ax.background_img(name="Blue Marble January", resolution=res_name)
        except Exception as e:
            # If resolution not available, show message
            ax.text(
                0.5,
                0.5,
                f"{res_name} resolution\nnot available",
                ha="center",
                va="center",
                transform=ax.transAxes,
            )
            continue

        # Zoom into Greek islands (Aegean Sea) to see detail differences clearly
        ax.set_extent([20, 28, 34, 41], crs=ccrs.PlateCarree())
        ax.coastlines(linewidth=0.5, color="white")

        ax.set_title(f"{res_name.capitalize()} ({res_size})", fontsize=11)

    plt.suptitle(
        "Resolution Comparison - Greek Islands (Aegean Sea)", fontsize=14, y=0.98
    )

    plt.savefig(output_path, dpi=150, bbox_inches="tight")
    print(f"  ✓ Saved to {output_path}")
    plt.close()


def main():
    """Run all examples."""
    # Get project root directory
    script_dir = Path(__file__).parent
    project_root = script_dir.parent
    images_json = project_root / "images.json"

    print("=" * 60)
    print("Cartopy BlueMarble Background Examples")
    print("=" * 60)
    print()

    # Setup Cartopy to use custom backgrounds
    if not setup_cartopy_backgrounds(images_json):
        sys.exit(1)

    print()

    # Create output directory
    output_dir = script_dir / "output"
    output_dir.mkdir(exist_ok=True)

    print(f"Generating examples (saving to {output_dir})...")
    print()

    try:
        # Run examples
        example_1_basic_map(output_dir / "example_1_basic_map.png")
        example_2_regional_map(output_dir / "example_2_regional_europe.png")
        example_3_different_projections(output_dir / "example_3_projections.png")
        example_4_seasonal_comparison(output_dir / "example_4_seasonal.png")
        example_5_resolution_comparison(output_dir / "example_5_resolutions.png")

        print()
        print("=" * 60)
        print("✓ All examples generated successfully!")
        print(f"  Output directory: {output_dir}")
        print("=" * 60)

    except Exception as e:
        print()
        print(f"Error generating examples: {e}")
        import traceback

        traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()
